
  CREATE UNIQUE INDEX KLIENS_PK ON CLIENT (ID ASC);
  

  CREATE UNIQUE INDEX "UZENET_PK" ON "MESSAGE" ("ID") ;


  CREATE UNIQUE INDEX "TABLE1_PK" ON "CLIENT_WORK_PLAN" ("CLIENT_ID", "WORKOUT_ID") ;


  CREATE UNIQUE INDEX "GYAKORLATSOROZAT_PK" ON "EX_SERIES" ("ID") ;


  CREATE UNIQUE INDEX "EDZESTERV_PK" ON "WORKOUT" ("ID") ;


  CREATE UNIQUE INDEX "GYAKORLAT_PK" ON "EXERCISE" ("ID") ;


  CREATE UNIQUE INDEX "EDZ_NAPI_FELOSZT_PK" ON "WORK_DAILY_SPLT" ("ID") ;
  

	ALTER TABLE CLIENT
	ADD CONSTRAINT KLIENS_PK PRIMARY KEY 
	(
	  ID 
	)
	USING INDEX KLIENS_PK
	ENABLE;


  ALTER TABLE "MESSAGE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGE" MODIFY ("SC_ID" NOT NULL ENABLE);
  ALTER TABLE "MESSAGE" MODIFY ("MSG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MESSAGE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MESSAGE" MODIFY ("DATESENT" NOT NULL ENABLE);
  ALTER TABLE "MESSAGE" ADD CONSTRAINT "UZENET_PK" PRIMARY KEY ("ID")
  USING INDEX "UZENET_PK"  ENABLE;
  ALTER TABLE "MESSAGE" MODIFY ("RC_ID" NOT NULL ENABLE);


  ALTER TABLE "EXERCISE_EX_SERIES" MODIFY ("EX_ID" NOT NULL ENABLE);
  ALTER TABLE "EXERCISE_EX_SERIES" MODIFY ("EX_SERIES_ID" NOT NULL ENABLE);


  ALTER TABLE "CLIENT_WORK_PLAN" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIENT_WORK_PLAN" MODIFY ("WORKOUT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIENT_WORK_PLAN" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CLIENT_ID", "WORKOUT_ID")
  USING INDEX "TABLE1_PK"  ENABLE;


  ALTER TABLE "EX_SERIES" MODIFY ("REPS" NOT NULL ENABLE);
  ALTER TABLE "EX_SERIES" MODIFY ("REP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "EX_SERIES" MODIFY ("SETS" NOT NULL ENABLE);
  ALTER TABLE "EX_SERIES" ADD CONSTRAINT "GYAKORLATSOROZAT_PK" PRIMARY KEY ("ID")
  USING INDEX "GYAKORLATSOROZAT_PK"  ENABLE;


  ALTER TABLE "WORKOUT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT" MODIFY ("DIFFICULTY" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT" ADD CONSTRAINT "EDZESTERV_PK" PRIMARY KEY ("ID")
  USING INDEX "EDZESTERV_PK"  ENABLE;


  ALTER TABLE "WORKOUT_DAILYSPL_EXERC" MODIFY ("EXERC_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT_DAILYSPL_EXERC" MODIFY ("WORKOUT_ID" NOT NULL ENABLE);


  ALTER TABLE "EXERCISE" MODIFY ("DIFFICULTY" NOT NULL ENABLE);
  ALTER TABLE "EXERCISE" MODIFY ("VIDEO" NOT NULL ENABLE);
  ALTER TABLE "EXERCISE" MODIFY ("PICTURE" NOT NULL ENABLE);
  ALTER TABLE "EXERCISE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "EXERCISE" ADD CONSTRAINT "GYAKORLAT_PK" PRIMARY KEY ("ID")
  USING INDEX "GYAKORLAT_PK"  ENABLE;


  ALTER TABLE "WORK_DAILY_SPLT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WORK_DAILY_SPLT" MODIFY ("DAY_PART" NOT NULL ENABLE);
  ALTER TABLE "WORK_DAILY_SPLT" MODIFY ("TIME" NOT NULL ENABLE);
  ALTER TABLE "WORK_DAILY_SPLT" ADD CONSTRAINT "EDZ_NAPI_FELOSZT_PK" PRIMARY KEY ("ID")
  USING INDEX "EDZ_NAPI_FELOSZT_PK"  ENABLE;


  ALTER TABLE "WORKOUT_DSPLIT" MODIFY ("SPLIT_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT_DSPLIT" MODIFY ("WORKOUT_ID" NOT NULL ENABLE);
  ALTER TABLE "WORKOUT_DSPLIT" MODIFY ("EX_NUMBER" NOT NULL ENABLE);
     
